"""Lean 4 verification with an explicit outcome taxonomy.

Design notes
------------
Pinning. Lean toolchain, Mathlib rev and the REPL must agree. We pin
a Mathlib *tag* whose name equals the Lean version (mathlib4 tag vX.Y.Z always
declares leanprover/lean4:vX.Y.Z), and lean_interact's REPL publishes a matching
`{repl_rev}_lean-toolchain-{lean_version}` tag. The historical failure was
Mathlib v4.32.2 against a REPL with no v4.32.2 tag -> "unexpected token" /
"unknown constant".

Speed. Importing Mathlib is the dominant cost by orders of
magnitude -- measured at >300s on this Windows box, versus seconds to elaborate
a single theorem. We import it ONCE into a base environment, snapshot that
environment to disk so later processes restore it instead of re-importing, and
run each snippet against it. Snippets whose imports differ from the base fall
back to a "fresh" run so that missing-import failures are still real failures
rather than being masked by the shared environment.

`sorry` detection. The REPL returns a structured `sorries` list. We use that,
NOT a regex over the source: `\\bsorry\\b` matches the word inside comments and
string literals and would mark genuinely complete proofs invalid.
"""

import os
import re
import subprocess
import time

# elan installs lake/lean/elan into ~/.elan/bin and adds it to PATH via the
# shell profile. A Python process started from a non-login shell — Colab cells,
# a notebook kernel, nohup, a CI step — never sources that profile, so `lake`
# is missing and setup dies with "lake: command not found" even though the
# install succeeded. Prepending it here fixes every such entry point at once.
# Ported from the code-validity branch, where it was found the hard way.
_ELAN_BIN = os.path.expanduser("~/.elan/bin")
if os.path.isdir(_ELAN_BIN) and _ELAN_BIN not in os.environ.get("PATH", "").split(os.pathsep):
    os.environ["PATH"] = _ELAN_BIN + os.pathsep + os.environ.get("PATH", "")

from config import (
    LEAN_TOOLCHAIN,
    LEAN_PROJECT_DIR,
    MATHLIB_REV,
    VERIFY_TIMEOUT_SECONDS,
    BASE_ENV_TIMEOUT_SECONDS,
    ENV_PICKLE_PATH,
    LEAN_MAX_REC_DEPTH,
    GOEDEL_LEAN4_HEADER,
)

# The outcome taxonomy. Never collapse these into a bare boolean.
VALID = "valid"
PARSE_FAILURE = "parse_failure"
EMPTY_CODE = "empty_code"
HAS_SORRY = "has_sorry"
COMPILE_ERROR = "compile_error"
# The GOAL was rejected, so the proof was never judged. Distinct from
# compile_error, which is a verdict on the model's proof. See
# statement_is_broken() and tests/diagnose_statement_failures.py.
STATEMENT_ERROR = "statement_error"
# The compiled file does not carry the dataset's statement, or carries more than
# one declaration, so whatever compiled is not a proof of the target. Distinct
# from compile_error: nothing was wrong with the Lean, it just proved the wrong
# thing. See verify_traces.py and audit finding 1-A.
STATEMENT_MISMATCH = "statement_mismatch"
# The proof compiled but depends on an axiom outside the Lean/Mathlib trusted
# set -- most importantly one the generation declared itself. A proof standing
# on `axiom cheat : 2 + 2 = 5` is not a proof. See audit finding 1-F.
UNSOUND_AXIOMS = "unsound_axioms"
TIMEOUT = "timeout"
VERIFIER_CRASH = "verifier_crash"

OUTCOMES = (VALID, PARSE_FAILURE, EMPTY_CODE, HAS_SORRY, COMPILE_ERROR,
            STATEMENT_ERROR, STATEMENT_MISMATCH, UNSOUND_AXIOMS, TIMEOUT,
            VERIFIER_CRASH)

# Axioms every ordinary Mathlib proof may stand on. Anything else -- above all a
# user-declared `axiom` -- makes the proof worthless as evidence.
TRUSTED_AXIOMS = frozenset({"propext", "Classical.choice", "Quot.sound"})

# Only `valid` counts as a proved theorem. Everything else is a distinct failure.
BASE_IMPORTS = ("Mathlib", "Aesop")

_IMPORT_RE = re.compile(r"^[ \t]*import[ \t]+([\w.]+)[ \t]*$", re.M)
_THM_NAME_RE = re.compile(
    r"^[ \t]*(?:@\[[^\]]*\]\s*)?"
    r"(?:private\s+|protected\s+|noncomputable\s+)*"
    r"(?:theorem|lemma)\s+([^\s:({\[]+)", re.M)
_AXIOM_DECL_RE = re.compile(r"^[ \t]*axiom\s+", re.M)
_AXIOM_MSG_RE = re.compile(r"depends on axioms:\s*\[([^\]]*)\]")

_DECL_RE = re.compile(
    r"^[ \t]*(?:@\[[^\]]*\]\s*)?"
    r"(?:private\s+|protected\s+|noncomputable\s+)*"
    r"(?:theorem|lemma|example|def|instance)\b",
    re.M,
)


def _lakefile_contents():
    # Keep the rationale in the generated file: setup_lean_project rewrites this
    # on every run, so anything not emitted here is lost the first time someone
    # runs setup.
    return (
        "# GENERATED by verifier.setup_lean_project — edit config.py, not this file.\n"
        "#\n"
        "# Pinned end-to-end. Do not bump any of these independently:\n"
        f"#   Lean toolchain : {LEAN_TOOLCHAIN}   (see ./lean-toolchain)\n"
        f"#   Mathlib rev    : {MATHLIB_REV}\n"
        "#   REPL           : augustepoiroux/repl @ v1.3.18, which publishes a\n"
        f"#                    matching tag v1.3.18_lean-toolchain-{MATHLIB_REV}\n"
        "#\n"
        "# mathlib4 tag vX.Y.Z always declares leanprover/lean4:vX.Y.Z in its\n"
        "# lean-toolchain, so naming the Mathlib tag after the Lean version is what\n"
        "# keeps all three in lockstep. The historical breakage was Mathlib v4.32.2\n"
        "# against a REPL with NO v4.32.2 tag -> 'unexpected token' /\n"
        "# 'unknown constant'.\n"
        "name = \"verification\"\n"
        "defaultTargets = [\"Verification\"]\n\n"
        "[[require]]\n"
        "name = \"mathlib\"\n"
        "git = \"https://github.com/leanprover-community/mathlib4.git\"\n"
        f"rev = \"{MATHLIB_REV}\"\n\n"
        "[[lean_lib]]\n"
        "name = \"Verification\"\n"
    )


def _manifest_mathlib_input_rev(manifest_path):
    """The mathlib `inputRev` a manifest records, or None if unreadable.

    Unreadable is deliberately not an error: the caller treats None as "cannot
    tell", which means "do not force an update on a guess".
    """
    try:
        import json
        with open(manifest_path, encoding="utf-8") as f:
            manifest = json.load(f)
    except (OSError, ValueError):
        return None
    for pkg in manifest.get("packages", []):
        if pkg.get("name") == "mathlib":
            return pkg.get("inputRev")
    return None


def setup_lean_project(project_dir=LEAN_PROJECT_DIR, verbose=True):
    """Create/refresh the pinned Lean project. Idempotent and safe to re-run.

    Never builds Mathlib from source: `lake exe cache get` always runs first.
    """
    os.makedirs(project_dir, exist_ok=True)

    # Always (re)write the pins so a stale checkout cannot drift.
    with open(os.path.join(project_dir, "lean-toolchain"), "w", encoding="utf-8") as f:
        f.write(f"{LEAN_TOOLCHAIN}\n")
    with open(os.path.join(project_dir, "lakefile.toml"), "w", encoding="utf-8") as f:
        f.write(_lakefile_contents())

    verification_file = os.path.join(project_dir, "Verification.lean")
    if not os.path.exists(verification_file):
        with open(verification_file, "w", encoding="utf-8") as f:
            f.write("import Mathlib\n")

    # A stale lakefile.lean from the old `lake new` path shadows lakefile.toml.
    legacy = os.path.join(project_dir, "lakefile.lean")
    if os.path.exists(legacy):
        os.rename(legacy, legacy + ".disabled")
        if verbose:
            print(f"[setup] renamed legacy {legacy} -> {legacy}.disabled")

    manifest = os.path.join(project_dir, "lake-manifest.json")
    built = os.path.isdir(os.path.join(project_dir, ".lake", "packages", "mathlib"))

    def run(args, check=True):
        if verbose:
            print(f"[setup] $ {' '.join(args)}")
        return subprocess.run(args, cwd=project_dir, check=check)

    # When to run `lake update` (issue #16).
    #
    # NOT for the reason first supposed. Our manifest records seven of Mathlib's
    # transitive deps with a floating inputRev (`main`/`master`) — aesop,
    # batteries, Qq, plausible, proofwidgets, importGraph, LeanSearchClient —
    # which looks like a drift vector and is not one. Mathlib is required at an
    # immutable TAG, and mathlib4 commits its own lake-manifest.json; lake
    # resolves a transitive dependency from that manifest rather than by
    # re-resolving the branch name. Measured on a clean clone: with aesop
    # `master` upstream at 18889deb, `lake update` still resolved aesop to
    # a7dbf0c6 — the revision mathlib v4.32.0 pins — and left our manifest
    # byte-identical. The floating inputRev is a record of how mathlib DECLARES
    # the requirement, not a live resolution target for us.
    #
    # What IS a real bug: the old condition was `not os.path.exists(manifest) or
    # not built`, which never consults config. Bump config.MATHLIB_REV on a box
    # that already has a built project and setup rewrites lakefile.toml with the
    # new rev, no `lake update` runs, and `lake build` quietly proceeds against
    # the OLD mathlib the stale manifest still pins. The version bump silently
    # does nothing.
    #
    # So: update when there is no manifest to honour, or when the manifest
    # disagrees with the pin config declares. Otherwise the manifest is
    # authoritative and `lake build` fetches at the revisions it records.
    manifest_rev = _manifest_mathlib_input_rev(manifest)
    stale = os.path.exists(manifest) and manifest_rev not in (None, MATHLIB_REV)

    if not os.path.exists(manifest):
        if verbose:
            print("[setup] no lake-manifest.json; resolving dependencies")
        run(["lake", "update"])
    elif stale:
        if verbose:
            print(f"[setup] manifest pins mathlib {manifest_rev!r} but config "
                  f"declares {MATHLIB_REV!r}; re-resolving")
        run(["lake", "update"])
    elif verbose:
        print("[setup] manifest agrees with config; honouring its pinned "
              "revisions (not running `lake update`)")

    # NEVER build Mathlib from source. Non-fatal: a project without Mathlib has
    # no `cache` executable.
    run(["lake", "exe", "cache", "get"], check=False)
    run(["lake", "build"])

    return project_dir


def split_prelude(code):
    """Return (imports, rest). `rest` keeps set_option/open and declarations."""
    imports = _IMPORT_RE.findall(code)
    rest = _IMPORT_RE.sub("", code)
    return imports, rest


def has_declaration(code):
    return bool(_DECL_RE.search(code))


class LeanVerifier:
    def __init__(
        self,
        project_dir=LEAN_PROJECT_DIR,
        timeout=VERIFY_TIMEOUT_SECONDS,
        setup=True,
        verbose=False,
    ):
        from lean_interact import Command, LeanREPLConfig, LeanServer
        from lean_interact.project import LocalProject

        self._Command = Command
        self.timeout = timeout
        self.project_dir = setup_lean_project(project_dir, verbose=verbose) if setup else project_dir

        project = LocalProject(directory=self.project_dir, auto_build=True)
        config = LeanREPLConfig(project=project, verbose=verbose)
        self.server = LeanServer(config)

        self.base_env, self.base_env_seconds, self.base_env_source = self._base_env()

    def _base_env(self):
        """Get an environment with Mathlib imported.

        `import Mathlib` costs minutes (>300s measured on Windows). It is a
        one-time cost per process, so we snapshot the resulting environment to
        disk and unpickle it in subsequent processes, which takes seconds.
        """
        from lean_interact import Command, PickleEnvironment, UnpickleEnvironment

        prelude = "\n".join(f"import {m}" for m in BASE_IMPORTS)

        if ENV_PICKLE_PATH and os.path.exists(ENV_PICKLE_PATH):
            t0 = time.perf_counter()
            try:
                resp = self.server.run(
                    UnpickleEnvironment(unpickle_env_from=ENV_PICKLE_PATH),
                    timeout=BASE_ENV_TIMEOUT_SECONDS,
                )
                env = getattr(resp, "env", None)
                if env is not None:
                    return env, time.perf_counter() - t0, "unpickled"
                print(f"[verifier] unpickle returned no env; rebuilding. {resp}")
            except Exception as e:  # noqa: BLE001 - fall back to a real import
                print(f"[verifier] unpickle failed ({type(e).__name__}: {e}); rebuilding.")

        t0 = time.perf_counter()
        resp = self.server.run(Command(cmd=prelude), timeout=BASE_ENV_TIMEOUT_SECONDS)
        env = getattr(resp, "env", None)
        elapsed = time.perf_counter() - t0
        if env is None:
            raise RuntimeError(f"Could not build base environment from {prelude!r}: {resp}")

        if ENV_PICKLE_PATH:
            try:
                os.makedirs(os.path.dirname(ENV_PICKLE_PATH), exist_ok=True)
                self.server.run(
                    PickleEnvironment(env=env, pickle_to=ENV_PICKLE_PATH),
                    timeout=BASE_ENV_TIMEOUT_SECONDS,
                )
                print(f"[verifier] snapshotted Mathlib env -> {ENV_PICKLE_PATH}")
            except Exception as e:  # noqa: BLE001 - snapshot is an optimisation
                print(f"[verifier] could not snapshot env ({type(e).__name__}: {e})")

        return env, elapsed, "imported"

    # ------------------------------------------------------------------ #

    def _classify(self, resp, elapsed, mode):
        messages = list(getattr(resp, "messages", []) or [])
        errors = [m for m in messages if getattr(m, "severity", None) == "error"]
        warnings = [m for m in messages if getattr(m, "severity", None) == "warning"]
        sorries = list(getattr(resp, "sorries", []) or [])

        # The REPL also reports sorry as a warning on the declaration.
        sorry_warning = any("sorry" in (getattr(w, "data", "") or "") for w in warnings)

        if errors:
            outcome = COMPILE_ERROR
        elif sorries or sorry_warning:
            outcome = HAS_SORRY
        elif getattr(resp, "env", None) is None:
            # FAIL CLOSED (audit finding 1-D). VALID used to be the bare `else`,
            # so a response carrying no messages AND no environment -- a dropped
            # command, a restore that did not restore, a schema skew -- scored as
            # a proved theorem. No environment means nothing was added to it,
            # which is not something we can call valid.
            outcome = VERIFIER_CRASH
            errors = list(errors) + [
                "REPL returned no environment and no messages; nothing was "
                "elaborated. Refusing to score this as valid."
            ]
        else:
            outcome = VALID

        return {
            "outcome": outcome,
            "valid": outcome == VALID,
            "errors": [getattr(e, "data", str(e)) for e in errors],
            "warnings": [getattr(w, "data", str(w)) for w in warnings],
            "num_errors": len(errors),
            "num_sorries": len(sorries),
            "seconds": round(elapsed, 3),
            "mode": mode,
        }

    def _axiom_audit(self, code, env, timeout):
        """After a clean compile, what does the theorem actually stand on?

        A compiling proof is only evidence if its axiom dependencies lie in the
        trusted set. `axiom cheat : 2 + 2 = 5` followed by `exact cheat`
        compiles perfectly and proves nothing -- measured at 9ms against this
        very verifier before this check existed (audit finding 1-F).

        We ask Lean, rather than grepping: `#print axioms` reports the real
        transitive dependency set, so it also catches an axiom pulled in through
        a lemma or a macro rather than declared in the file.

        Returns (ok: bool, detail: str).
        """
        m = _THM_NAME_RE.search(code)
        if m is None:
            # No named theorem to interrogate. Fall back to the static check so
            # a self-declared axiom still cannot pass unnoticed.
            if _AXIOM_DECL_RE.search(code):
                return False, "file declares its own `axiom` and has no named theorem to audit"
            return True, "no named theorem; no axiom declaration present"

        name = m.group(1)
        try:
            resp = self.server.run(
                self._Command(cmd=f"#print axioms {name}", env=env), timeout=timeout
            )
        except Exception as e:  # noqa: BLE001 - an un-auditable proof is not a pass
            return False, f"axiom audit failed ({type(e).__name__}: {e})"

        msgs = " ".join(
            (getattr(m_, "data", "") or "") for m_ in (getattr(resp, "messages", []) or [])
        )
        if "does not depend on any axioms" in msgs:
            return True, "depends on no axioms"

        found = _AXIOM_MSG_RE.search(msgs)
        if not found:
            # Could not read the dependency set. Do not guess in the permissive
            # direction; fall back to the static check.
            if _AXIOM_DECL_RE.search(code):
                return False, f"file declares its own `axiom`; could not read #print axioms output: {msgs[:120]}"
            return True, f"could not parse #print axioms output: {msgs[:120]}"

        used = {a.strip() for a in found.group(1).split(",") if a.strip()}
        extra = sorted(used - TRUSTED_AXIOMS)
        if extra:
            return False, "proof depends on untrusted axiom(s): " + ", ".join(extra)
        return True, "axioms: " + ", ".join(sorted(used))

    def verify(self, lean_code, timeout=None):
        """Verify one snippet. Always returns a dict carrying `outcome`."""
        timeout = self.timeout if timeout is None else timeout
        t0 = time.perf_counter()

        if lean_code is None or not lean_code.strip():
            return {
                "outcome": EMPTY_CODE, "valid": False, "errors": [], "warnings": [],
                "num_errors": 0, "num_sorries": 0, "seconds": 0.0, "mode": "none",
            }

        imports, rest = split_prelude(lean_code)

        if not has_declaration(rest):
            # Header-only or prose-only: nothing was proved. Not a Lean failure,
            # but emphatically not `valid` either.
            return {
                "outcome": EMPTY_CODE, "valid": False, "errors": [], "warnings": [],
                "num_errors": 0, "num_sorries": 0, "seconds": 0.0, "mode": "none",
            }

        # Elaboration budget, applied here rather than in the prompt header so
        # that verification config never alters what the model was asked.
        rec = f"set_option maxRecDepth {LEAN_MAX_REC_DEPTH}\n"

        # Fast path only when the snippet's imports are exactly the base set.
        # Otherwise run standalone so a missing import is a real failure rather
        # than being masked by the shared environment.
        use_base = bool(imports) and set(imports) <= set(BASE_IMPORTS)
        if use_base:
            cmd = rec + rest
        else:
            # Imports must stay first, so the option goes after them.
            cmd = "\n".join(f"import {m}" for m in imports) + "\n" + rec + rest
        env = self.base_env if use_base else None
        mode = "shared_env" if use_base else "fresh"

        try:
            resp = self.server.run(self._Command(cmd=cmd, env=env), timeout=timeout)
        except TimeoutError:
            elapsed = time.perf_counter() - t0
            self._restart()
            return {
                "outcome": TIMEOUT, "valid": False,
                "errors": [f"verification exceeded {timeout}s"], "warnings": [],
                "num_errors": 0, "num_sorries": 0,
                "seconds": round(elapsed, 3), "mode": mode,
            }
        except Exception as e:  # noqa: BLE001 - any REPL failure is a crash outcome
            elapsed = time.perf_counter() - t0
            self._restart()
            return {
                "outcome": VERIFIER_CRASH, "valid": False,
                "errors": [f"{type(e).__name__}: {e}"], "warnings": [],
                "num_errors": 0, "num_sorries": 0,
                "seconds": round(elapsed, 3), "mode": mode,
            }

        res = self._classify(resp, time.perf_counter() - t0, mode)

        # Only a clean compile needs auditing; everything else already failed.
        if res["outcome"] == VALID:
            ok, detail = self._axiom_audit(rest, getattr(resp, "env", None), timeout)
            res["axioms"] = detail
            if not ok:
                res = dict(res, outcome=UNSOUND_AXIOMS, valid=False,
                           errors=list(res["errors"]) + [detail])
        return res

    def statement_is_broken(self, formal_statement, timeout=None):
        """Does the STATEMENT alone fail, with no model proof involved?

        Called only after a `compile_error`, to decide whether Lean was judging
        the model's proof or refusing the goal before reaching it. The statement
        is verified with `sorry` as its entire proof: a well-formed goal then
        returns `has_sorry`, and anything that still errors was never a test of
        the prover.

        This is a re-verification, not a regex over the error text — it
        generalises past the two causes we happen to have seen (pre-v4.32
        big-operator syntax, and binder-level `Finset` defaults) to any
        statement Lean will not accept.

        Returns (broken: bool, detail: str).
        """
        if not (formal_statement or "").strip():
            return False, "no formal_statement on the record"

        stmt = formal_statement.rstrip()
        if not re.search(r"\bby\s*\Z", stmt):
            stmt += " := by" if not stmt.endswith(":=") else " by"
        probe = f"{GOEDEL_LEAN4_HEADER}{stmt}\n  sorry\n"

        res = self.verify(probe, timeout=timeout)
        if res["outcome"] == HAS_SORRY:
            return False, "statement elaborates; the failure is in the proof"
        if res["outcome"] == VALID:
            # `sorry` was not needed: the statement is closed by its own
            # elaboration. Unusual, but it is not a broken statement.
            return False, "statement closes without a proof"
        detail = res["errors"][0].strip().splitlines()[0][:200] if res["errors"] else res["outcome"]
        return True, detail

    def _restart(self):
        """A timed-out REPL is killed by lean_interact; rebuild the session."""
        try:
            from lean_interact import Command, LeanREPLConfig, LeanServer
            from lean_interact.project import LocalProject

            project = LocalProject(directory=self.project_dir, auto_build=False)
            self.server = LeanServer(LeanREPLConfig(project=project, verbose=False))
            prelude = "\n".join(f"import {m}" for m in BASE_IMPORTS)
            resp = self.server.run(Command(cmd=prelude), timeout=300)
            self.base_env = getattr(resp, "env", None)
        except Exception as e:  # noqa: BLE001
            print(f"[verifier] restart failed: {type(e).__name__}: {e}")
            self.base_env = None
