"""Render results/GPU_TACTIC_RECOVERY.md from GPU_TACTIC_RECOVERY.json.

Generated, not hand-typed, for the reason results/regenerate_reports.py exists:
a number transcribed by hand into prose is a number that can drift from its
artifact. Every figure below is read from the JSON.
"""
import io
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
sys.path.insert(0, _ROOT)
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

R = lambda *p: os.path.join(_ROOT, *p)


def ci(d):
    lo, hi = d.get("ci", [None, None])
    return "—" if lo is None else "[%.1f–%.1f]" % (lo, hi)


def kn(d):
    if d.get("n") in (None, 0):
        return "—"
    return "**%d/%d = %.1f%%**" % (d["k"], d["n"], d["pct"])


def curve_row(label, c, key):
    v = c.get(key)
    if not v:
        return "| %s | — | — | — |" % label
    return "| %s | **%.1f%%** | [%.1f–%.1f] | [%.1f–%.1f] |" % (
        label, v["pct"], v["wilson_ci"][0], v["wilson_ci"][1],
        v["boot_ci"][0], v["boot_ci"][1])


def mc(x):
    """One line of a McNemar block."""
    return ("| %s | %d | %s | %s | %d | %d | %d | %.3f | %s |" % (
        x["subgroup"], x["n_pairs"],
        kn(x["armA_doc_comment"]), kn(x["armB_no_doc_comment"]),
        x["b_A_pass_B_fail"], x["c_A_fail_B_pass"], x["n_discordant"],
        x["mcnemar_exact_p"],
        "yes" if x["can_possibly_reach_p05"] else "**no**"))


def main():
    d = json.load(io.open(R("results", "GPU_TACTIC_RECOVERY.json"), encoding="utf-8"))
    meta = d.get("run", {})
    E1 = d["experiment1_doc_comment_ablation"]
    E2 = d["experiment2_best_of_n"]
    E3 = d["experiment3_error_feedback_repair"]
    L = []
    W = L.append

    W("# GPU tactic recovery — three experiments on tactic selection\n")
    W("Generated by `tests/audit/gpu_recovery_report.py` from "
      "`results/GPU_TACTIC_RECOVERY.json`. Every figure is read from that "
      "artifact; none is transcribed by hand.\n")
    W("**Headline is always pass@1.** Best-of-n and repair appear below it as "
      "separate, labelled measurements and never replace it.\n")
    W("**FormalStep and NuminaMath Stage B are different pipelines with "
      "different units and are never pooled** (`CURRENT_NUMBERS.md`). Neither "
      "are the two experiment-1 sets: the baseline set is 50 CoT steps of ONE "
      "problem, so its rows are clustered, not independent.\n")
    W("\n---\n")

    # ---------------- Experiment 1 ----------------
    W("## Experiment 1 — does the doc comment mislead the prover?\n")
    W("Paired, T=0.0 greedy, one trajectory. Arm A renders `informal_prefix` as "
      "the `current_step` doc comment; arm B renders it as the empty string. "
      "`PROMPT_TEMPLATE`, `GOEDEL_LEAN4_HEADER`, `TOP_P` and the extraction "
      "regex are untouched — the unified diff between an arm-A and an arm-B "
      "prompt is exactly the one `/-- ... -/` line.\n")
    for name, title in (("n50_distinct", "n50 distinct (50 problems, independent rows)"),
                        ("baseline_50step", "baseline 50-step (50 steps of ONE problem — clustered)")):
        S = E1.get(name)
        if not S or S.get("error"):
            continue
        W("\n### %s\n" % title)
        W("| subgroup | pairs | arm A (doc comment) | arm B (none) | b | c | discordant | McNemar p | can reach p<.05 |")
        W("|---|---|---|---|---|---|---|---|---|")
        for k in ("overall", "statement_false", "not_statement_false"):
            W(mc(S[k]))
        W("")
        W("`b` = passed with the doc comment and failed without it. `c` = the "
          "reverse. The exact test needs **%d** discordant pairs before any "
          "split can reach p<0.05.\n"
          % S["overall"]["min_discordant_for_any_significance"])
        rep = S.get("armA_reproduces_committed_run")
        if rep:
            W("**Control — arm A against the committed run** (`%s`): %s → %s, "
              "per-row agreement %s, rows that flipped: %s.\n" % (
                  rep["reference"], kn(rep["committed"]), kn(rep["armA_now"]),
                  kn(rep["per_row_agreement"]),
                  rep["rows_that_flipped"] or "none"))
        sf = S["statement_false"]
        vd = sf.get("vacuity_of_discordant", {})
        nv = sf.get("net_of_vacuous")
        if vd.get("c_rows"):
            W("**The `statement_false` cell, gated.** Arm B's wins are rows %s, "
              "of which %s are vacuous. Net of vacuity: arm A %s, arm B %s, "
              "b=%d, c=%d, p=%.3f.\n" % (
                  vd["c_rows"], vd["c_vacuous"] or "none",
                  kn(nv["armA_doc_comment"]), kn(nv["armB_no_doc_comment"]),
                  nv["b_A_pass_B_fail"], nv["c_A_fail_B_pass"],
                  nv["mcnemar_exact_p"]))

    # ---------------- Experiment 2 ----------------
    W("\n---\n")
    W("## Experiment 2 — best-of-n\n")
    W("k=16 samples per problem at T=0.7, top_p=0.95. pass@k uses the unbiased "
      "estimator `1 - C(n-c,k)/C(n,k)`, not \"did any of the first k pass\", "
      "which is biased upward.\n")
    W("Two intervals are given because pass@k is a MEAN of per-problem "
      "estimates rather than a raw binomial count: Wilson over problems (exact "
      "at k=n, approximate below it) and a percentile bootstrap resampling "
      "problems. **Quote the bootstrap where they disagree.**\n")
    for name, title in (("formalstep_n50", "FormalStep — n50 distinct"),
                        ("stageb_n90", "NuminaMath Stage B — n=90")):
        S = E2.get(name)
        if not S or S.get("error"):
            W("\n### %s\n\n_not available_\n" % title)
            continue
        W("\n### %s (%d problems x %s samples = %d)\n"
          % (title, S["n_problems"], S["samples_per_problem"], S["total_samples"]))
        W("| k | pass@k | Wilson 95% | bootstrap 95% |")
        W("|---|---|---|---|")
        for k in (1, 2, 4, 8, 16):
            W(curve_row("pass@%d" % k, S["curve"], "pass@%d" % k))
        W("")
        if S.get("pass16_minus_pass1_pp") is not None:
            W("**pass@16 − pass@1 = %+.1f pp.** That is what tactic-selection "
              "diversity buys on this set.\n" % S["pass16_minus_pass1_pp"])
        c1 = S["curve"].get("pass@1")
        if c1:
            W("Problems solved by at least one of the 16 samples: **%d/%d**.\n"
              % (c1["n_solved_by_any"], S["n_problems"]))
        vc = S.get("vacuous_curve")
        W("**Gates.** Every pass above already cleared the axiom scan and "
          "`statement_mismatch` — %d samples were rejected as "
          "`statement_mismatch` and %d as `unsound_axioms`.\n"
          % (S["gates"]["statement_mismatch"], S["gates"]["unsound_axioms"]))
        if vc:
            W("**Vacuous passes, separately at each k** (%d of the problems in "
              "the pass set have a goal the probe ladder closes without a "
              "proof):\n" % S["n_vacuous_problems_in_pass_set"])
            W("| k | vacuous pass@k |")
            W("|---|---|")
            for k in (1, 2, 4, 8, 16):
                v = vc.get("pass@%d" % k)
                W("| pass@%d | %s |" % (k, "—" if not v else "%.1f%%" % v["pct"]))
            W("")
        else:
            W("_No problem in this set's pass set has a vacuous goal._\n")
        if S.get("by_band"):
            W("**By difficulty band:**\n")
            W("| band | pass@1 | pass@16 | delta |")
            W("|---|---|---|---|")
            for bn, bc in S["by_band"].items():
                a, b = bc.get("pass@1"), bc.get("pass@16")
                W("| %s | %s | %s | %s |" % (
                    bn,
                    "—" if not a else "%.1f%%" % a["pct"],
                    "—" if not b else "%.1f%%" % b["pct"],
                    "—" if not (a and b) else "%+.1f pp" % (b["pct"] - a["pct"])))
            W("")

    # ---------------- Experiment 3 ----------------
    W("\n---\n")
    W("## Experiment 3 — one error-feedback repair attempt\n")
    if E3.get("error"):
        W("\n_not available_\n")
    else:
        W("Run on the **%s**. The retry prompt is the original prompt, the "
          "model's failed attempt, and Lean's error verbatim — no hints, no "
          "tactic suggestions.\n" % E3["set"])
        W("**One-shot and with-repair are separate rows and are not merged.**\n")
        W("| row | rate | 95% CI |")
        W("|---|---|---|")
        W("| one-shot on this set | %s | %s |"
          % (kn(E3["one_shot_baseline"]["rate"]), ci(E3["one_shot_baseline"]["rate"])))
        W("| with one repair (pooled) | %s | %s |"
          % (kn(E3["with_repair_pooled"]), ci(E3["with_repair_pooled"])))
        for p, r in E3["by_pipeline"].items():
            W("| — with repair, %s | %s | %s |" % (p, kn(r), ci(r)))
        W("")
        W("_%s_\n" % E3["pooling_caveat"])
        if E3.get("retry_changed_the_proof"):
            W("The retry produced a different proof body on **%s** of attempts; "
              "on the rest the model reproduced its own failed proof.\n"
              % E3["retry_changed_the_proof"])
        orc = E3.get("oracle_reference")
        if orc:
            W("**Against the tactic oracle**, which ran the same 104: "
              "substantive recoveries %s. %s\n"
              % (orc["substantive_recoveries"], orc["note"]))

    W("\n---\n")
    W("## The four questions\n")
    for q in d.get("answers", []):
        W("**%s**\n\n%s\n" % (q["q"], q["a"]))

    if meta:
        W("\n---\n")
        W("## Cost, provenance, and disposition\n")
        for k, v in meta.items():
            W("- **%s:** %s" % (k.replace("_", " "), v))

    out = R("results", "GPU_TACTIC_RECOVERY.md")
    io.open(out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s (%d lines)" % (out, len(L)))


if __name__ == "__main__":
    main()
