"""Audit the PASS set, not the problem categories. Issue #13.

`statement_arithmetic` and the sample-42 vacuity defect are one bug pointing two
directions. A false dataset statement either

  (a) cannot be closed, the model fails, and we log `compile_error` -- scoring
      the dataset's error against the prover; measured at 36-62% of failures in
      results/FAILURE_TAXONOMY.md; or

  (b) makes the hypotheses mutually inconsistent, `False` follows, every goal
      follows, a proof of it compiles, and we log a PASS.

(a) was measured. (b) was not, and it is the direction that flatters us. This
pass measures (b).

Method, and why it is not a grep
--------------------------------
Vacuity is decided by HYPOTHESIS CONSISTENCY, never by tactic name. Two
independent methods, run against the same 37 passes:

  1. LEAN (results/vacuity_scan.json). For each pass, probe
     `theorem contra_probe <binders> : False` with simp_all / omega /
     norm_num at *. If `False` is provable from the hypotheses alone, every goal
     is, and the pass is vacuous. This asks the prover, not the source text.

  2. STATIC (statement_truth_scan.label_row). Bind every hypothesis of the form
     `var = <closed expr>` and re-evaluate every other claim under that
     environment, in exact arithmetic. Catches a false hypothesis whose
     contradiction the three tactics happen not to find.

Agreement between two methods with different failure modes is the evidence. Each
one alone is a lower bound.

Reads only committed artifacts. No Lean, no GPU -- the Lean work is already in
vacuity_scan.json.
Run: python tests/audit/pass_set_audit.py
"""

import collections
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from statement_truth_scan import label_row  # noqa: E402
from provenance import split_binders_goal  # noqa: E402
from stats import wilson, pct  # noqa: E402

N_SAMPLES = 50
OUT_MD = os.path.join(ROOT, "results", "PASS_SET_AUDIT.md")

J = lambda p: [json.loads(l) for l in io.open(os.path.join(ROOT, p), encoding="utf-8")
               if l.strip()]
LOAD = lambda p: json.load(io.open(os.path.join(ROOT, p), encoding="utf-8"))

# Vacuity classes, ordered by how little the goal demands. Classes 1-4 assert
# nothing; class 5 is real arithmetic but no reasoning; only class 6 needs an
# inference step.
ASSERTS_NOTHING = ("1_goal_is_True", "2_hypotheses_contradictory",
                   "3_goal_restates_a_hypothesis", "4_syntactic_tautology")
GROUND = "5_ground_computation"
CONTENTFUL = "6_contentful"
CONTRADICTORY = "2_hypotheses_contradictory"


def audit_temperature(T):
    vac = {r["sample"]: r for r in LOAD("results/vacuity_scan.json")[T]}
    traces = {r["sample_index"]: r for r in J(f"traces/temp{T}_n50_1each/traces.jsonl")}

    rows = []
    for i, r in sorted(vac.items()):
        stmt = traces[i]["formal_statement"]
        props, _goal = split_binders_goal(stmt)
        static_label, static_detail, _ = label_row(stmt)
        rows.append({
            "sample": i,
            "class": r["class"],
            "lean_contra": bool(r["contra"]),
            "has_binders": bool(props),
            "static_label": static_label,
            "static_false_hypothesis": static_label in (
                "false_hypothesis", "false_hypothesis_and_goal"),
            "static_detail": static_detail,
        })
    return rows


def main():
    doc_rows = {}
    md = []
    md.append("# Auditing the pass set\n")
    md.append(
        "Generated by `tests/audit/pass_set_audit.py` from committed artifacts. "
        "No number below is hand-typed.\n\n"
        "**The question.** A false dataset statement damages the measurement in "
        "two directions. It either cannot be closed — the model fails and we log "
        "`compile_error`, scoring the dataset's error against the prover — or it "
        "makes the hypotheses mutually inconsistent, in which case `False` "
        "follows, every goal follows, a proof compiles, and we log a **pass**. "
        "The first direction was measured. The second was not, and it is the one "
        "that flatters us.\n\n"
        "**Vacuity is decided by hypothesis consistency, never by tactic name.** "
        "Two methods with different failure modes are run over the same passes: a "
        "Lean probe for `False` from the hypotheses alone, and an exact-arithmetic "
        "static evaluation that substitutes bindings before checking. Neither is "
        "authoritative alone; their agreement is the evidence.\n")

    for T in ("0.0", "0.2"):
        rows = audit_temperature(T)
        doc_rows[T] = rows
        n_pass = len(rows)
        cls = collections.Counter(r["class"] for r in rows)

        contra = [r["sample"] for r in rows if r["class"] == CONTRADICTORY]
        static = [r["sample"] for r in rows if r["static_false_hypothesis"]]
        no_binders = [r["sample"] for r in rows if not r["has_binders"]]
        probed = [r["sample"] for r in rows if r["has_binders"]]

        asserts_nothing = sum(cls[c] for c in ASSERTS_NOTHING)

        md.append(f"\n## T = {T}\n")
        md.append(f"{n_pass} passes of {N_SAMPLES} samples.\n")

        md.append("\n### Method agreement\n")
        md.append("| | samples |")
        md.append("|---|---|")
        md.append(f"| Lean `False`-probe fires (hypotheses inconsistent) | "
                  f"{contra or '—'} |")
        md.append(f"| Static analysis finds a false hypothesis | {static or '—'} |")
        md.append(f"| **Agreement** | "
                  f"**{'yes — identical sets' if set(contra) == set(static) else 'NO — investigate'}** |")
        md.append(f"| Passes with no binders (cannot be vacuous this way) | "
                  f"{len(no_binders)} of {n_pass} |")
        md.append(f"| Passes actually probed | {len(probed)} of {n_pass} |")
        md.append(
            f"\nA statement with no hypotheses cannot have inconsistent ones, so "
            f"the {len(no_binders)} unprobed passes are unprobed by construction, "
            f"not by omission.\n")

        md.append("\n### What the passes assert\n")
        md.append("| class | n | share of passes |")
        md.append("|---|---|---|")
        for c in ASSERTS_NOTHING + (GROUND, CONTENTFUL):
            if cls[c]:
                md.append(f"| `{c}` | {cls[c]} | {pct(cls[c] / n_pass)} |")

        md.append("\n### Corrected pass rates\n")
        md.append("| what is being counted | rate | 95% Wilson |")
        md.append("|---|---|---|")
        for label, k in (
            ("compile rate — a proof of the target compiled", n_pass),
            ("minus vacuous passes (hypotheses inconsistent)", n_pass - len(contra)),
            ("minus every pass that asserts nothing", n_pass - asserts_nothing),
            ("minus ground arithmetic too — the reasoning rate", cls[CONTENTFUL]),
        ):
            lo, hi = wilson(k, N_SAMPLES)
            md.append(f"| {label} | **{k}/{N_SAMPLES} = {pct(k / N_SAMPLES)}** | "
                      f"[{pct(lo)}–{pct(hi)}] |")

        md.append(
            f"\n**Removing vacuous passes moves 74% to "
            f"{pct((n_pass - len(contra)) / N_SAMPLES)} — one sample.** The larger "
            f"correction is not vacuity but triviality: "
            f"{asserts_nothing} of {n_pass} passes assert nothing at all.\n")

        if contra:
            r = next(x for x in rows if x["sample"] == contra[0])
            md.append(f"\n### The vacuous pass — sample {r['sample']}\n")
            md.append("```")
            md.append(r["static_detail"])
            md.append("```")
            md.append(
                "\nEvery hypothesis is arithmetically false and they are mutually "
                "inconsistent, so `False` follows and therefore every goal does. "
                "The proof compiles, proves the stated goal, and stands on no "
                "untrusted axiom — every existing check passes. See issue #13.\n")

    # ---------------------------------------------------------------- #
    truth_path = os.path.join(ROOT, "results", "statement_truth_scan.json")
    if os.path.exists(truth_path):
        t = LOAD("results/statement_truth_scan.json")
        checkable = t["checkable_rows"]
        md.append("\n---\n")
        md.append("\n## How much of the benchmark asserts false things\n")
        md.append(
            f"The sampled 50 are not the benchmark. `tests/audit/"
            f"statement_truth_scan.py` evaluates the closed arithmetic of every "
            f"one of the **{t['rows']:,} statements** across all "
            f"**{t['problems']} problems**.\n")
        md.append(
            f"\n{checkable:,} of {t['rows']:,} rows "
            f"({pct(checkable / t['rows'])}) have at least one claim that "
            f"evaluates to a closed value. That is the only honest denominator: a "
            f"row whose claims never close is not evidence either way and leaves "
            f"both sides.\n")
        md.append("\n| | n | share of checkable |")
        md.append("|---|---|---|")
        for label, k in (
            ("statement asserts something **false**", t["false_any"]),
            ("…of which a **false hypothesis** — the vacuity-producing class",
             t["false_hypothesis_any"]),
            ("…of which only a **false goal** — simply unprovable",
             t["false_goal_only"]),
        ):
            lo, hi = wilson(k, checkable)
            md.append(f"| {label} | {k:,}/{checkable:,} | **{pct(k / checkable)}** "
                      f"[{pct(lo)}–{pct(hi)}] |")

        aff, nprob = t["problems_with_a_false_step"], t["problems"]
        lo, hi = wilson(aff, nprob)
        md.append(
            f"\n**Per problem: {aff} of {nprob} problems contain at least one "
            f"arithmetically false step — {pct(aff / nprob)}** [{pct(lo)}–{pct(hi)}].\n")
        md.append(
            "\nThe false-hypothesis class is the one that can manufacture a pass. "
            "It is the smaller share, which is consistent with finding exactly one "
            "vacuous pass in the sampled 50 — but it is not zero, and it scales "
            "with the eval set.\n")
        md.append(
            "\n**Scope.** This finds statements whose *closed arithmetic* is false. "
            "It cannot see a statement false for a non-arithmetic reason, and it "
            "says nothing about the 40% of rows whose claims never close. Every "
            "number above is a lower bound on how much of FormalStep is wrong.\n")

    with io.open(OUT_MD, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(md) + "\n")

    print("\n".join(md))
    print(f"\nwrote {OUT_MD}")


if __name__ == "__main__":
    main()
