"""Generate results/STAGE_B_NUMINAMATH.md from the committed Stage B artifacts.

Reads results/stage_b_traces.jsonl and results/stage_b_verified.jsonl. No number
in the report is hand-typed.

Run: python tests/audit/stage_b_report.py
"""

import collections
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from provenance import classify  # noqa: E402
from provenance import proof_claims, split_at_by, domain_of  # noqa: E402
from failure_taxonomy import summarize, FAILURE_KINDS  # noqa: E402
from stats import wilson, pct, two_proportion_z  # noqa: E402

OUT = os.path.join(ROOT, "results", "STAGE_B_NUMINAMATH.md")
BANDS = ("easy", "medium", "hard")
# Outcomes that are not verdicts on the model's proof (verifier.py).
EXCLUDED = {"parse_failure", "timeout", "statement_error", "statement_mismatch",
            "verifier_crash"}
_IMPORT = re.compile(r"^[ \t]*import[ \t]+[\w.]+[ \t]*$", re.M)

J = lambda p: [json.loads(l) for l in io.open(os.path.join(ROOT, p), encoding="utf-8")
               if l.strip()]


def main():
    traces = {r["uuid"]: r for r in J("results/stage_b_traces.jsonl")}
    ver = J("results/stage_b_verified.jsonl")
    L = []
    a = L.append

    a("# Stage B — Goedel-Prover-SFT on NuminaMath-LEAN Number Theory\n")
    a("Generated by `tests/audit/stage_b_report.py` from the committed artifacts. "
      "No number below is hand-typed.\n")
    a("90 whole problems, 30 from each Kimina-Prover-72B `win_rate` band, "
      "temperature 0, one trajectory each. Generated on a Lambda A10; verified "
      "against our pinned Mathlib v4.32.0.\n")

    a("\n## Pass rate against the Kimina ceiling\n")
    a("Kimina-Prover-72B's `win_rate` is that model's own measured RL success "
      "rate on the same problems. It is the ceiling, not a baseline we match "
      "methodology with.\n")
    a("\n| band | ours | 95% Wilson | Kimina ceiling |")
    a("|---|---|---|---|")
    per = {}
    for b in BANDS:
        s = [x for x in ver if x["band"] == b]
        k = sum(1 for x in s if x["trace_valid"])
        lo, hi = wilson(k, len(s))
        wr = sum(x["wr"] for x in s) / len(s)
        per[b] = (k, len(s))
        a(f"| {b} | **{k}/{len(s)} = {pct(k/len(s))}** | [{pct(lo)}–{pct(hi)}] | {wr:.3f} |")
    tot = sum(1 for x in ver if x["trace_valid"])
    lo, hi = wilson(tot, len(ver))
    a(f"| **total** | **{tot}/{len(ver)} = {pct(tot/len(ver))}** | [{pct(lo)}–{pct(hi)}] | — |")

    a("\nOn the testable-only denominator (excluding outcomes that are not "
      "verdicts on the proof — `parse_failure`, `timeout`, `statement_error`):\n")
    a("\n| band | testable | excluded |")
    a("|---|---|---|")
    for b in BANDS:
        s = [x for x in ver if x["band"] == b]
        t = [x for x in s if x["outcome"] not in EXCLUDED]
        k = sum(1 for x in t if x["trace_valid"])
        lo, hi = wilson(k, len(t))
        a(f"| {b} | **{k}/{len(t)} = {pct(k/len(t))}** [{pct(lo)}–{pct(hi)}] | {len(s)-len(t)} |")

    a("\n## It is two levels, not three\n")
    a("| comparison | | z | p | |")
    a("|---|---|---|---|---|")
    for x, y in (("easy", "medium"), ("medium", "hard"), ("easy", "hard")):
        k1, n1 = per[x]; k2, n2 = per[y]
        z, p = two_proportion_z(k1, n1, k2, n2)
        a(f"| {x} vs {y} | {k1}/{n1} vs {k2}/{n2} | {z:.2f} | **{p:.4f}** | "
          f"{'separates' if p < 0.05 else '**does not separate**'} |")
    a("\n**`easy` separates from the other two. `medium` and `hard` do not "
      "separate from each other at n=30.** Report this as two levels — a "
      "tractable band and a hard band — not as a three-point curve. The "
      "underlying `win_rate` means do differ (0.944 / 0.608 / 0.147), but our "
      "sample cannot resolve the lower two.\n")

    a("\n## Failure taxonomy\n")
    a("```")
    a(summarize(ver)["table"])
    a("```")
    a("\n`unknown_identifier` is the notable one: the model naming Mathlib lemmas "
      "that do not exist. It is far more common here than on FormalStep, where it "
      "accounted for 1 of 29 baseline failures — competition problems push the "
      "model toward inventing lemmas.\n")

    a("\n## The arithmetic split is NOT ANSWERABLE with the current labeller\n")
    fails = [x for x in ver if not x["trace_valid"]]
    checked = 0
    for r in fails:
        t = traces[r["uuid"]]
        code = _IMPORT.sub("", t.get("full_code") or "").lstrip()
        _, body = split_at_by(code)
        _bad, n, _lits = proof_claims(body, domain_of(t["formal_statement"]))
        checked += n
    counts = collections.Counter()
    for r in fails:
        t = dict(traces[r["uuid"]])
        t["formal_statement"] = _IMPORT.sub("", t["formal_statement"]).lstrip()
        counts[classify(r, t)[0]] += 1
    a("The question was whether `proof_false` — a failure caused by a number the "
      "MODEL wrote — stays at zero on whole-problem olympiad Number Theory, as it "
      "did on FormalStep.\n")
    a("\n**It cannot be answered from this run.** Two reasons, in order of "
      "severity:\n")
    a(f"\n1. **The labeller evaluated {checked} proof-side claims across all "
      f"{len(fails)} failures.** A zero from a denominator of {checked} is "
      "guaranteed by construction, not measured. `ARITHMETIC_FINDINGS.md` § "
      "Limits documents the same problem on FormalStep: 1 claim assertable "
      "across 55 failures.")
    a("\n2. **Before the `%` fix it reported 9 `proof_false`, and all 9 were "
      "spurious** — `a^2 % 3 = 1` misread as `3 = 1`. Nine flags, nine false "
      "positives, so it had no demonstrated precision on modular arithmetic. The "
      "fix stops the misreads but does not make modular claims checkable.\n")
    a("\nLabels actually assigned, reported for completeness and not as a result:\n")
    a("\n| label | n | share |")
    a("|---|---|---|")
    for k, v in counts.most_common():
        a(f"| `{k}` | {v} | {pct(v/len(fails))} |")
    a(f"\n`UNKNOWN` at {pct(counts.get('UNKNOWN',0)/len(fails))} is itself a "
      "signal that the labeller — built and validated against FormalStep's "
      "shapes — does not transfer cleanly to olympiad statements.\n")

    a("\n## Do not compare this to the 72%\n")
    a("The FormalStep figure is **step-level**: one row per chain-of-thought "
      "step, ~62 per problem. This is **problem-level**: one row per whole "
      "problem. Different units.\n")
    a("\nThe step-level number is additionally inflated by a triviality mode this "
      "dataset structurally cannot produce — see "
      "`STEP_VS_PROBLEM_TRIVIALITY.md`. All 90 statements here classify "
      "`6_contentful` under the same six probes, so **these pass rates need no "
      "content-rate correction**; 31% is already a content rate.\n")

    a("\n## Generation notes\n")
    tk = [traces[x["uuid"]].get("generated_tokens", 0) for x in ver]
    a(f"\n| | |")
    a("|---|---|")
    a(f"| fence-extracted | {sum(1 for x in ver if traces[x['uuid']].get('full_code'))}/{len(ver)} |")
    a(f"| truncated at the 2048-token budget | {sum(1 for x in ver if traces[x['uuid']].get('truncated'))} |")
    a(f"| generated tokens | mean {sum(tk)/len(tk):.0f}, max {max(tk)} |")
    for b in BANDS:
        s = [traces[x["uuid"]].get("generated_tokens", 0) for x in ver if x["band"] == b]
        a(f"| mean tokens, {b} | {sum(s)/len(s):.0f} |")
    a("\nToken count rises monotonically with difficulty, an independent signal "
      "that the band ordering is real.\n")

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
