"""Phases 2-4: read results/tactic_oracle.jsonl and write results/TACTIC_ORACLE.md.

Separated from tactic_oracle.py so the writeup can be regenerated without
re-running Lean.

Run: python tests/audit/tactic_oracle_report.py
"""
import collections, io, json, os, sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
for _p in (_HERE, _ROOT):
    if _p not in sys.path:
        sys.path.insert(0, _p)
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import tactic_common as tc  # noqa: E402
from tactic_oracle import LADDER, CONTRA_TACTICS  # noqa: E402
from config import VERIFY_TIMEOUT_SECONDS  # noqa: E402
from stats import wilson  # noqa: E402

# Denominator and numerator for the headline validity rate of each run, taken
# from results/CURRENT_NUMBERS.md. `n` is every attempted sample, not the judged
# subset -- the corrected rate has to sit on the same denominator as the
# published one or the two are not comparable.
HEADLINE = {
    "stageB_T0.0": (28, 90, "stage_b_verified_temp0.0.jsonl"),
    "stageB_T0.7": (26, 90, "stage_b_verified_temp0.7.jsonl"),
    "formalStep_baseline_50step_1problem": (21, 50, "verification_temp_0.jsonl"),
    "formalStep_n50_distinct_T0.0": (37, 50, "verify3_temp0.0.jsonl"),
    "formalStep_n50_distinct_T0.2": (37, 50, "verify3_temp0.2.jsonl"),
}

VERDICTS = [
    ("recovered", "closed by a standard tactic (**genuine recovery**)"),
    ("vacuous_close", "closed only via inconsistent hypotheses (**vacuous, not a recovery**)"),
    ("none_closed", "no tactic in the ladder closed it"),
    ("budget", "exceeded budget"),
    ("excluded_no_code", "excluded: no `full_code` to take a header from"),
]


def md(headers, rows):
    out = ["| " + " | ".join(str(h) for h in headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def pct(k, n):
    return "—" if not n else "%.1f%%" % (100.0 * k / n)


def ci(k, n):
    if not n:
        return "—"
    lo, hi = wilson(k, n)
    return "[%.1f–%.1f]" % (100 * lo, 100 * hi)


def main():
    path = os.path.join(_ROOT, "results", "tactic_oracle.jsonl")
    rows = tc.J(path)
    by_id = {(r["set"], str(r["id"])): r for r in rows}
    samples = tc.attach_lean_errors(tc.load_samples())
    for s in samples:
        s["oracle"] = by_id.get((s["set"], str(s["id"])))
    done = [s for s in samples if s["oracle"]]
    n = len(done)
    partial = n < len(samples)

    v = lambda r: r["oracle"]["verdict"]
    counts = collections.Counter(v(s) for s in done)

    L = []
    A = L.append
    A("# Phase 2–4 — the tactic oracle: how many recorded failures are the "
      "prover's fault?\n")
    if partial:
        A("> ⚠️ **PARTIAL RUN — %d of %d samples completed.** Every figure below "
          "is computed on the completed subset and will move when the run "
          "finishes. Do not quote it.\n" % (n, len(samples)))
    A("`tactic_mismatch` is 77.3% [68.6–84.1] of Stage B's judged failures: the "
      "statement elaborated, the goal stood, and the model's tactic did not "
      "close it. Every one of those is logged `compile_error` and scores the "
      "trace invalid — so prover weakness is being counted as trace invalidity. "
      "This phase measures how much of it there is, by throwing the model's "
      "proof away and trying a fixed ladder of standard tactics on the "
      "identical goal.\n")
    A("Generated by `tests/audit/tactic_oracle.py` (the Lean run) and "
      "`tests/audit/tactic_oracle_report.py` (this file). Raw per-attempt "
      "record: `results/tactic_oracle.jsonl`.\n")

    # ------------------------------------------------------------------ method
    A("## 1. The ladder, in full\n")
    A("Fixed in advance, identical for every sample, tried in this order; the "
      "first rung that closes the goal wins. Reproduced here so the run can be "
      "repeated exactly.\n")
    A("```")
    for i, (name, tac) in enumerate(LADDER, 1):
        A("%2d. %-18s %s" % (i, name, tac))
    A("```")
    A("")
    A("Rungs 1–5 and 8–11 are the audit brief's pre-registered list verbatim. "
      "Two notes on rungs 6 and 7:\n")
    A("- **Rung 6 is the brief's `nlinarith [sq_nonneg _, sq_nonneg _]`, run "
      "verbatim.** The `_` placeholders cannot be synthesised from the goal, so "
      "the rung raises an elaboration error rather than attempting a proof. It "
      "is kept, and its behaviour reported, so that the pre-registered ladder is "
      "on the record as written.\n")
    A("- **Rung 7 is bare `nlinarith`, added because rung 6 cannot run.** It is "
      "the only sample-independent form: any concrete hint term (`sq_nonneg "
      "(x - y)`) would have to be read off the individual goal, which is exactly "
      "the per-sample tuning this audit forbids. Rung 7 is applied identically "
      "to every sample and was fixed before the run started.\n")

    A("### What was and was not changed\n")
    A("- The statement is untouched: same binders, same hypotheses, same goal.\n")
    A("- The header is untouched. The prefix handed to Lean is `full_code` cut "
      "at the end of the statement, so it carries the Goedel header **and the "
      "`informal_prefix` doc comment** exactly as the model saw them. Only the "
      "text after `:= by` differs.\n")
    A("- Per-attempt wall clock is **%ds**, the main verifier's "
      "`VERIFY_TIMEOUT_SECONDS`. A sample that exhausts it is `budget`, never "
      "`none_closed`.\n" % VERIFY_TIMEOUT_SECONDS)
    A("- Every close runs the axiom audit the main verifier runs (`#print "
      "axioms`), so a proof standing on an untrusted axiom is not scored valid.\n")
    A("- **Every close then runs the vacuity probe**: `theorem contra_probe "
      "<binders> : False := by %s`. If `False` follows from the hypotheses "
      "alone, the goal was closable because the hypotheses are inconsistent, and "
      "that is not a recovery — it is another sample 42. Those are counted in "
      "their own row and excluded from the recovery count.\n"
      % " / ".join("`%s`" % t for t in CONTRA_TACTICS))

    # ------------------------------------------------------------------ results
    A("## 2. Results, per trace set\n")
    hdr = ["", "Stage B T=0.0", "Stage B T=0.7", "FormalStep baseline",
           "FormalStep n50 T=0.0", "FormalStep n50 T=0.2", "**all**"]
    setrows = [[s for s in done if s["set"] == st] for st in tc.SET_ORDER]
    rows = []
    for key, label in VERDICTS:
        if key == "excluded_no_code" and not counts[key]:
            continue
        cells = []
        for grp in setrows:
            k = sum(1 for s in grp if v(s) == key)
            cells.append("%d  (%s)" % (k, pct(k, len(grp))) if grp else "—")
        cells.append("**%d  (%s)**" % (counts[key], pct(counts[key], n)))
        rows.append([label] + cells)
    rows.append(["**n (tactic_mismatch failures)**"]
                + ["**%d**" % len(g) for g in setrows] + ["**%d**" % n])
    A(md(hdr, rows))
    A("")
    A("Percentages are the share of that set's `tactic_mismatch` failures.\n")

    rec = counts["recovered"]
    vac = counts["vacuous_close"]
    lo, hi = wilson(rec, n) if n else (0, 0)
    A("> **A standard tactic closes %d of %d = %s %s of the failures the "
      "labeller called `tactic_mismatch`.** A further %d closed only because "
      "the hypotheses are contradictory and are not counted as recoveries.\n"
      % (rec, n, pct(rec, n), ci(rec, n), vac))

    # ------------------------------------------------------------------ rungs
    A("## 3. Which rung did the work\n")
    rung = collections.Counter(s["oracle"]["rung"] for s in done
                               if v(s) == "recovered")
    rows = []
    tacmap = dict(LADDER)
    for name, tac in LADDER:
        k = rung.get(name, 0)
        rows.append(["`%s`" % tac, k, pct(k, n), pct(k, rec) if rec else "—"])
    A(md(["rung", "genuine recoveries", "share of all %d" % n,
          "share of the %d recoveries" % rec], rows))
    A("")
    if rung:
        top, topk = rung.most_common(1)[0]
        A("**The single most valuable substitution is `%s`**, which alone "
          "accounts for %d of the %d recoveries (%s of all `tactic_mismatch` "
          "failures).\n" % (tacmap[top], topk, rec, pct(topk, n)))
    else:
        A("No rung produced a genuine recovery.\n")

    vrung = collections.Counter(s["oracle"]["rung"] for s in done
                                if v(s) == "vacuous_close")
    if vrung:
        A("Rungs that closed a goal **vacuously** (excluded above): "
          + ", ".join("`%s` %d" % (tacmap[k], c) for k, c in vrung.most_common())
          + ".\n")

    # rung 6 behaviour
    r6 = collections.Counter()
    for s in done:
        for a in s["oracle"].get("attempts", []):
            if a["rung"] == "nlinarith_hint":
                r6[a["outcome"]] += 1
    if r6:
        A("### Rung 6 as literally specified\n")
        A("`nlinarith [sq_nonneg _, sq_nonneg _]` was attempted on %d samples "
          "and its outcomes were: %s. "
          % (sum(r6.values()), ", ".join("`%s` %d" % (k, c) for k, c in r6.most_common())))
        heads = collections.Counter()
        for s in done:
            for a in s["oracle"].get("attempts", []):
                if a["rung"] == "nlinarith_hint" and a["error_head"]:
                    heads[a["error_head"][:90]] += 1
        if heads:
            A("Most common message: `%s` (%d×). "
              % (heads.most_common(1)[0][0], heads.most_common(1)[0][1]))
        A("It closed %d goals. This is why rung 7 exists.\n"
          % rung.get("nlinarith_hint", 0))

    # ------------------------------------------------------------------ shape
    A("## 4. Recovery by goal shape and by the tactic the model chose\n")
    A("Where the headroom actually is.\n")
    shapes = [sh for sh in tc.SHAPES if any(s["shape"] == sh for s in done)]
    rows = []
    for sh in shapes:
        grp = [s for s in done if s["shape"] == sh]
        k = sum(1 for s in grp if v(s) == "recovered")
        rows.append([sh, len(grp), k, pct(k, len(grp)), ci(k, len(grp))])
    A(md(["goal shape (top-level)", "n", "recovered", "rate", "95% CI"], rows))
    A("")
    rows = []
    for t, c in collections.Counter(s["lean_tactic"] for s in done).most_common():
        grp = [s for s in done if s["lean_tactic"] == t]
        k = sum(1 for s in grp if v(s) == "recovered")
        rows.append(["`%s`" % t, len(grp), k, pct(k, len(grp)), ci(k, len(grp))])
    A(md(["tactic Lean named as failing", "n", "recovered", "rate", "95% CI"], rows))
    A("")
    st_grp = [s for s in done if s["structural"]]
    st_rec = sum(1 for s in st_grp if v(s) == "recovered")
    if st_grp:
        A("Phase 1 identified **%d** failures as structural category errors on "
          "direct evidence from Lean. The oracle recovers **%d of those %d "
          "(%s %s)** — the cleanest read on whether \"this tactic could never "
          "have worked\" implies \"a working tactic exists\".\n"
          % (len(st_grp), st_rec, len(st_grp), pct(st_rec, len(st_grp)),
             ci(st_rec, len(st_grp))))

    # ------------------------------------------------------------------ phase 3
    A("## 5. Phase 3 — what it does to the headline\n")
    A("The corrected rate is **not what Goedel-Prover achieves**. It is what the "
      "pass rate would be **if tactic selection were perfect** — an upper bound "
      "on the trace-validity signal. The gap between the two columns is the size "
      "of the prover-skill contamination in the current metric. The two numbers "
      "are only meaningful side by side and must never be reported apart.\n")
    hdr = ["trace set", "observed pass rate", "95% CI", "genuine recoveries",
           "pass rate under tactic oracle (**upper bound**)", "95% CI", "gap"]
    rows = []
    for st in tc.SET_ORDER:
        k, tot, _art = HEADLINE[st]
        r = sum(1 for s in done if s["set"] == st and v(s) == "recovered")
        rows.append([tc.SET_LABEL[st],
                     "%d/%d = %s" % (k, tot, pct(k, tot)), ci(k, tot), r,
                     "%d/%d = %s" % (k + r, tot, pct(k + r, tot)), ci(k + r, tot),
                     "+%.1f pp" % (100.0 * r / tot)])
    A(md(hdr, rows))
    A("")
    A("**No row is pooled with another.** FormalStep and Stage B are different "
      "formalization pipelines with different units; the three FormalStep runs "
      "are three runs over overlapping problems and their passes are not "
      "independent. Each row stands alone.\n")
    sb0 = HEADLINE["stageB_T0.0"]
    r0 = sum(1 for s in done if s["set"] == "stageB_T0.0" and v(s) == "recovered")
    A("> Stage B T=0.0, the repo's headline Stage B figure: **observed "
      "%d/%d = %s %s; under a perfect tactic oracle %d/%d = %s %s.** The second "
      "number is an upper bound that no prover attains, and the %.0f-point gap "
      "is how much of the current metric is measuring Goedel-Prover's tactic "
      "selection rather than the validity of the trace.\n"
      % (sb0[0], sb0[1], pct(sb0[0], sb0[1]), ci(sb0[0], sb0[1]),
         sb0[0] + r0, sb0[1], pct(sb0[0] + r0, sb0[1]), ci(sb0[0] + r0, sb0[1]),
         100.0 * r0 / sb0[1]))

    # ------------------------------------------------------------------ phase 4
    A("## 6. Phase 4 — the three questions, in plain language\n")

    A("### 6.1 What fraction of our recorded failures are the prover's fault "
      "rather than the trace's?\n")
    A("**%s %s of `tactic_mismatch` failures — %d of %d — are the prover's "
      "fault in the strictest sense available: keep the statement and the "
      "header exactly as they were, replace the proof with a fixed standard "
      "tactic, and the goal closes.** " % (pct(rec, n), ci(rec, n), rec, n))
    A("Two things bound that number in opposite directions. It is a **lower** "
      "bound on prover fault, because a ladder of %d standard tactics is a weak "
      "prover: a goal that needs a lemma, an induction, or a case split is "
      "counted `none_closed` here even when a competent proof exists. It is an "
      "**upper** bound on what *this* pipeline could recover without new "
      "generation, because the oracle is allowed to know the answer and the "
      "model is not.\n" % len(LADDER))
    A("Scaled to the whole failure set rather than to `tactic_mismatch` alone: "
      "`tactic_mismatch` is 85 of Stage B's 110 judged failures, so a %s "
      "recovery rate within it is %s of Stage B's judged failures overall.\n"
      % (pct(rec, n), pct(int(round(85 * rec / n)) if n else 0, 110)))

    A("### 6.2 Does the headline validity number understate trace validity, and "
      "by how much?\n")
    if rec:
        A("**Yes, and by the gap in §5.** ")
    else:
        A("**On this evidence, no — or not measurably.** ")
    for st in ("stageB_T0.0", "stageB_T0.7"):
        k, tot, _ = HEADLINE[st]
        r = sum(1 for s in done if s["set"] == st and v(s) == "recovered")
        A("%s moves %s → %s (+%.1f pp). " % (tc.SET_LABEL[st], pct(k, tot),
                                             pct(k + r, tot), 100.0 * r / tot))
    A("\n")
    A("The honest framing: the published rate is a **joint measurement of trace "
      "validity and prover skill**, and it cannot be decomposed without a "
      "reference prover. The oracle rate replaces \"Goedel-Prover's tactic "
      "choice\" with \"the best of %d fixed tactics\", which is a different "
      "prover, not no prover. It brackets the contamination; it does not remove "
      "it.\n" % len(LADDER))

    A("### 6.3 Which single tactic substitution would recover the most "
      "failures?\n")
    if rung:
        top, topk = rung.most_common(1)[0]
        A("**`%s`** — %d of the %d recoveries, %s of all `tactic_mismatch` "
          "failures. " % (tacmap[top], topk, rec, pct(topk, n)))
        rest = [(tacmap[k], c) for k, c in rung.most_common()[1:4]]
        if rest:
            A("Behind it: " + ", ".join("`%s` (%d)" % (a, b) for a, b in rest) + ".\n")
        else:
            A("\n")
    else:
        A("None. No rung recovered a goal.\n")

    A("## 7. What this cannot settle without new generation\n")
    A("Everything above reuses existing traces. Three questions need a fresh "
      "generation run and are logged as `requires-a-new-run`.\n")
    A("1. **Best-of-n sampling.** The oracle asks whether *a* correct proof "
      "exists in a fixed tactic list. It does not ask whether Goedel-Prover "
      "would *find* one given more attempts. Those are different quantities and "
      "this audit measures only the first. n=1 at two temperatures is all the "
      "repo has, and McNemar already says temperature does nothing (p = 0.80); "
      "sampling breadth is the untested axis.\n")
    A("2. **An error-feedback repair loop.** Lean's messages here are "
      "unusually actionable — `linarith failed to find a contradiction` printed "
      "with the full context, `omega could not prove the goal` printed with a "
      "counterexample to its own constraint system. Feeding that back and "
      "resampling is the standard repair loop and it has never been tried in "
      "this repo. The oracle is a crude lower bound on what it would achieve, "
      "because the oracle cannot read the error it just caused.\n")
    A("3. **Does the `informal_prefix` doc comment steer tactic choice? — the "
      "most interesting untested hypothesis here.** The prompt carries the CoT "
      "step as a Lean doc comment immediately above the statement, so the model "
      "reads the natural-language reasoning before choosing a tactic. Sample 27's "
      "output says *\"By simplifying the right-hand side\"*, which is exactly "
      "what its doc comment `/-- $= 1\\cdot (100+6)^3$. -/` suggests. If the CoT "
      "step is wrong or misleading, it may be **actively steering the prover "
      "into the wrong tactic** — which would mean the pipeline is not measuring "
      "trace validity so much as measuring whether the trace misleads a prover. "
      "That is a different research question wearing the same clothes.\n")
    A("   The ablation is cheap and decisive: regenerate with "
      "`informal_prefix=\"\"`, everything else pinned, and compare pass rates "
      "and tactic distributions on the same statements. If the pass rate rises "
      "with the doc comment removed, the CoT step is hurting the prover. If the "
      "tactic distribution shifts but the pass rate does not, it steers without "
      "helping. Needs a GPU; nothing else in this audit does.\n")

    A("## 8. Limits of this measurement\n")
    A("- **The ladder is weak on purpose.** %d fixed tactics, no lemma lookup, "
      "no induction, no case analysis, no hint terms. `none_closed` means \"this "
      "ladder failed\", never \"the goal is unprovable\".\n" % len(LADDER))
    A("- **The oracle is not a prover and must not be added to the pipeline.** "
      "It is a measurement of headroom. Wiring it into generation would make "
      "the pass rate uninterpretable, because the ladder was chosen after "
      "seeing which goals fail.\n")
    A("- **`recovered` is a claim about the goal, not about the model.** It says "
      "a correct proof of that statement exists within reach of standard "
      "automation. It says nothing about whether the CoT step the statement "
      "formalises is good reasoning.\n")
    A("- **Vacuous closes are reported, not hidden.** %d goals closed because "
      "their hypotheses are contradictory. Those statements are broken in the "
      "sample-42 way and are excluded from every recovery figure above.\n" % vac)
    A("- The `tactic_mismatch` label itself comes from a labeller that "
      "evaluated **0 arithmetic claims on Stage B** (`STAGEB_PROVENANCE.md` §3). "
      "This audit inherits that label without re-deriving it, so it inherits its "
      "reach problem too.\n")

    io.open(os.path.join(_ROOT, "results", "TACTIC_ORACLE.md"), "w",
            encoding="utf-8").write("\n".join(L) + "\n")

    summary = {
        "complete": not partial, "n_done": n, "n_total": len(samples),
        "ladder": [{"rung": a, "tactic": b} for a, b in LADDER],
        "per_attempt_budget_seconds": VERIFY_TIMEOUT_SECONDS,
        "counts": dict(counts),
        "recovered_wilson": [round(lo, 4), round(hi, 4)],
        "by_set": {st: dict(collections.Counter(
            v(s) for s in done if s["set"] == st)) for st in tc.SET_ORDER},
        "recovering_rung": dict(rung),
        "vacuous_rung": dict(vrung),
        "headline": {st: {"observed_k": HEADLINE[st][0], "n": HEADLINE[st][1],
                          "recoveries": sum(1 for s in done if s["set"] == st
                                            and v(s) == "recovered")}
                     for st in tc.SET_ORDER},
    }
    json.dump(summary, io.open(os.path.join(_ROOT, "results", "tactic_oracle.json"),
                               "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print("wrote results/TACTIC_ORACLE.md and results/tactic_oracle.json")
    print("done=%d/%d  recovered=%d  vacuous=%d  none=%d  budget=%d"
          % (n, len(samples), rec, vac, counts["none_closed"], counts["budget"]))


if __name__ == "__main__":
    main()
